### ISSUE TITLE
REST API 설계시

### ISSUE THREAD

**Issue by SHIN1501020** [SHIN1501020/nodejs_lv1#1]
URI에 밑줄(_)를 사용하지 않는다는 글을 봤다. 

param를 사용하는 부분에서 밑줄(_)을 사용했는데
'/:_postId'
이것도 REST API 설계 규칙에 어긋나는 부분인가?

**Comment by ohbin-kwon** [comment]
안녕하세요 혜훤님. :_postId를 실제 uri에서 사용한다고 생각해볼게요.

www.server.com이 혜훤님이 만든 서버입니다. 그리고 어떤 라우터(GET 메서드)가 '/post/:_postId'라는 path를 가진다고 합시다. 
그럼 실제로 클라이언트가 _postId가 1인 경우 호출할때, 'www.server.com/post/1' 로 호출하게 됩니다. 따라서 클라이언트가 사용할때는 _기호는 볼수없습니다. 
<img width="371" alt="image" src="https://github.com/SHIN1501020/nodejs_lv1/assets/77604219/bc134ea9-82cb-4bc1-8b3d-7277b2d0e60a">

혜훤님이 보신 경우는  3번과 같은 경우를 말씀하시는것 같네요(https://khj93.tistory.com/entry/%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC-REST-API%EB%9E%80-REST-RESTful%EC%9D%B4%EB%9E%80)
