### ISSUE TITLE
4-1=0 리뷰

### ISSUE THREAD

**Issue by kimjonghwa230412** [SHIN1501020/nodejs_lv1#3]
1. joi 라이브러리를 활용한 데이터 유효성 검사 코드가 아주 꼼꼼하고 대단합니다!
2. post router에서 map을 활용해 원하는 데이터만 조회할 수 있도록 작성한 방법!
  잘 배웠습니다!
4. 스키마 설계를 굉장히 꼼꼼하게 했다는게 느껴집니다! dotenv를 활용한 환경변수 설정까지
   잘 배웠습니다!아주 꼼꼼하고 대단합니다!

**Comment by SHIN1501020** [comment]
:D
